name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - 
        name Check out the repo
        uses: actions/checkout@v2
      - 
        name: Fetch Dependencies
        run: docker pull lacledeslan/steamcmd:linux && docker pull debian:buster-slim
      - 
        name: Build Image
        run: docker build . -f linux.Dockerfile -t lacledeslan/gamesvr-csgo --no-cache --build-arg BUILDNODE=GitHub;
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
