name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: get base image
      run: docker pull lacledeslan/steamcmd:linux && docker pull debian:buster-slim
    - name: Build the Docker image
      run: docker build . --file linux.Dockerfile --tag lacledeslan/gamesvr-csgo:latest --no-cache --build-arg BUILDNODE=GitHub
